name: Lint

on:
  push:
    branches:
      - main

jobs:
  flake8:
    runs-on: ubuntu-latest
    container: python:3.12-slim-bullseye
    steps:
      - uses: actions/checkout@v3
      - name: Install flake8
        run: pip install flake8==7.1.0 flake8-quotes==3.4.0 flake8-commas==4.0.0
      - name: Run flake8
        run: flake8 --count --show-source --statistics
