name: Test

on:
  push:
    branches:
      - main

jobs:
  unittest:
    runs-on: ubuntu-latest
    container: python:3.12-slim-bullseye
    services:
      postgres:
        image: kartoza/postgis:15
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
      redis:
        image: redis
    steps:
      - uses: actions/checkout@v3
      - name: Install flake8
        run: pip install poetry
      - name: Install os dependencies
        run: apt-get install --no-install-recommends build-essential apt-utils procps libgdal-dev gettext curl dos2unix -y
      - name: Install poetry
        run: |
          poetry install
          poetry config virtualenvs.create false
      - name: Run test
        run: python manage.py test
